BEGIN;

DROP TABLE IF EXISTS flag_contexts;
DROP TABLE IF EXISTS user_profiles;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS role_types;
DROP TABLE IF EXISTS flags;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS projects;

COMMIT;